### ISSUE TITLE
Error: Cannot find module './../node'

### ISSUE THREAD

**Issue by nitinsurana** [rauchg/slackin#203] opened 2016-06-18 09:58 UTC
Running `node slackin` after cloning locally throws the following error :

```
2016-06-18T07:45:37.731955+00:00 app[web.1]: Error: Cannot find module './../node'
2016-06-18T07:45:37.731956+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-06-18T07:45:37.731957+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-06-18T07:45:37.731957+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-06-18T07:45:37.731958+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-18T07:45:37.731958+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/slackin:5:15)
2016-06-18T07:45:37.731959+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-06-18T07:45:37.731960+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-06-18T07:45:37.731960+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-06-18T07:45:37.731961+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
```

**Comment by alexpls** [comment] 2016-06-18 10:20
I get this issue too after cloning the repo, doing an `npm install`, then `node ./bin/slackin`.

Looks like it's caused by this recent commit: c54b6786ea71edc25af36335bcbc6c5c6fbb57e7, as running slackin on the commit just before it works without issue.

**Comment by alexpls** [comment] 2016-06-18 10:38
Found an issue where the location of the slackin library had not been updated in `bin/slackin` to reflect the changes made on commit c54b678. PR created to resolve this: https://github.com/rauchg/slackin/pull/204.

**Comment by nitinsurana** [comment] 2016-06-18 11:39
Changed `node` to `dist` locally and tried deploying on heroku. Now it gives

```Sat Jun 18 2016 11:36:50 GMT+0000 (UTC) – listening on 0.0.0.0:NaN
2016-06-18T11:37:47.049320+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-06-18T11:37:47.049429+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-06-18T11:37:48.136159+00:00 heroku[web.1]: Process exited with status 137
2016-06-18T11:37:48.157192+00:00 heroku[web.1]: State changed from starting to crashed
```

Any idea, what is missing ?

**Comment by nitinsurana** [comment] 2016-06-18 11:49
Removing `--port` from Procfile seems to fix the issue.

**Comment by alexpls** [comment] 2016-06-19 08:31
@nitinsurana I think the port issue might be something to do with how you're deploying rather than with this issue. Did you specify a `PORT` environment variable in the Heroku admin panel?

**Comment by benoitc** [comment] 2016-06-19 13:30
@alexpls i also got this error with no `PORT` variable set. Right now the deployement to heroku doesn't work :(

**Comment by nitinsurana** [comment] 2016-06-19 19:29
@alexpls Heroku should automatically provide an environment variable. https://devcenter.heroku.com/articles/dynos#local-environment-variables

**Comment by alexpls** [comment] 2016-06-20 09:34
@nitinsurana you're right, looks like the port variable somehow ends up as NaN when fetched from the environment.

**Comment by alexpls** [comment] 2016-06-20 10:24
@nitinsurana I've found a potential cause of your port issue and have raised it separately here: #206

**Comment by mdo** [comment] 2016-06-20 16:56
Having similar issues here for our Bootstrap Slack channel. Switched to a fork of the project as mentioned in https://github.com/rauchg/slackin/issues/205#issuecomment-227041443 and it's back up and successfully deploying for me.

**Comment by thiagogcm** [comment] 2016-06-21 03:19
@alexpls I tried using your PR fix and now I have de following error

```
/app/dist/slack.js:59
        var team = res.body.team;
                      ^

TypeError: Cannot read property 'body' of undefined
    at /app/dist/slack.js:59:23
    at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
    at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at emitErrorNT (net.js:1265:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```


did you manage to run it on heroku?

**Comment by leo** [comment] 2016-06-23 09:10
The "port issue" has been fixed in version `v1.3.0` of [args](https://github.com/leo/args). So please vote for [this PR](https://github.com/rauchg/slackin/pull/208), so that the dependency gets updated! :blush:

The other issue regarding to "./../node" has been fixed in https://github.com/rauchg/slackin/pull/204, so please vote for that as well.

All in all, IMHO, we can now close this issue.

**Comment by loretoparisi** [comment] 2016-06-23 13:42
I have the same very error running the `Dockerfile`:

```shell
macbookproloreto:slackin admin$ docker run -it -e SLACK_SUBDOMAIN=xxx -e SLACK_COC=http://example.com -e SLACK_API_TOKEN=xxxxxxxxxxx -e SLACK_CHANNELS=xxxx -e PORT=3000 $CONTAINERID
module.js:327
    throw err;
    ^

Error: Cannot find module 'node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/www/bin/slackin:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
macbookproloreto:slackin admin$ 
```

It seems that within the `docker` container the `node` folder has not been created.

**Comment by loretoparisi** [comment] 2016-06-24 10:18
So entering the `docker` container:

```shell
macbookproloreto:slackin admin$ docker run -it b51fb4977d59 /bin/sh
/srv/www # ls
Dockerfile         LICENSE.md         README.md          azuredeploy.json   dist               lib                package.json       test
HISTORY.md         Procfile           app.json           bin                gulpfile.babel.js  node_modules       scripts            web.config
```

I cannot see the `/node` folder, as it builds on my mac. It seems in the `docker` alpine it does not.

**Comment by leo** [comment] 2016-06-24 11:03
@loretoparisi As I've mentioned above, all of this has been fixed in https://github.com/rauchg/slackin/pull/208. The bug has appeared because the build output directory was renamed from "node" to "dist", but the path within the code hasn't yet been adjusted. If you need to deploy now, use my fork! 😊

**Comment by loretoparisi** [comment] 2016-06-24 12:06
@leo that is why I have the `dist/` folder there...

**Comment by leo** [comment] 2016-06-24 12:28
@loretoparisi Exactly!

**Comment by loretoparisi** [comment] 2016-06-24 12:44
@leo thank you it runs

So this is my command now

```shell
docker run -it -e SLACK_SUBDOMAIN=xxxxxx -e SLACK_COC=http://example.com -e SLACK_API_TOKEN=xxxxxxxxx -e SLACK_CHANNELS=xxxxx -e PORT=9000 -e WEBSITE_HOSTNAME=localhost:9000 slackinmxm
```

it starts listening now:

```shell
Fri Jun 24 2016 12:42:15 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 12:42:16 GMT+0000 (UTC) – listening on 2036872716ec:NaN
Fri Jun 24 2016 12:42:16 GMT+0000 (UTC) – ready
WARN: no logo configured
Fri Jun 24 2016 12:42:16 GMT+0000 (UTC) – online 0, total 2 
Fri Jun 24 2016 12:42:21 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 12:42:22 GMT+0000 (UTC) – online 0, total 2 (+566ms)
Fri Jun 24 2016 12:42:27 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 12:42:27 GMT+0000 (UTC) – online 0, total 2 (+556ms)
Fri Jun 24 2016 12:42:32 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 12:42:33 GMT+0000 (UTC) – online 0, total 2 (+561ms)
Fri Jun 24 2016 12:42:38 GMT+0000 (UTC) – fetching
```

but cannot get the port binding to `localhost:9000` working locally.

**Comment by leo** [comment] 2016-06-24 13:20
Does setting `-p` make it work?

**Comment by loretoparisi** [comment] 2016-06-24 15:21
@leo it seems no

```shell
macbookproloreto:bin admin$ docker run -it -e SLACK_SUBDOMAIN=xxxx -e SLACK_COC=http://example.com -e SLACK_API_TOKEN=xxxx -e SLACK_CHANNELS=xxxx -e PORT=9000 -e WEBSITE_HOSTNAME=localhost:9000 -p 9000:9000 slackinmxm
Fri Jun 24 2016 15:19:50 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 15:19:50 GMT+0000 (UTC) – listening on 27e884253b8d:NaN
Fri Jun 24 2016 15:19:51 GMT+0000 (UTC) – ready
WARN: no logo configured
```

using `-p 9000:9000`

**Comment by loretoparisi** [comment] 2016-06-24 15:34
@leo uhm very strange

```shell
$docker run -it -e SLACK_SUBDOMAIN=xxxx -e SLACK_COC=http://example.com -e SLACK_API_TOKEN=xxxx -e SLACK_CHANNELS=xxx -e PORT=9000 -e WEBSITE_HOSTNAME=localhost:9000 -p 9000 slackinmxm
Fri Jun 24 2016 15:33:12 GMT+0000 (UTC) – fetching
Fri Jun 24 2016 15:33:12 GMT+0000 (UTC) – listening on d13ce8ad59b0:NaN
```

the same w/o `WEBSITE_HOSTNAME`

**Closed** 2016-06-24 23:00 UTC

**Comment by gtyler** [comment] 2016-08-17 17:57
FYI - Same error now when trying to deploy to Heroku via the "Deploy" button: https://cl.ly/21012P3y0G1u

@rauchg any ideas?

**Comment by avatsaev** [comment] 2016-09-07 05:43
getting same issue on heroku? what's going on?

**Comment by nitinsurana** [comment] 2016-09-07 06:28
@avatsaev please see my comments for a possible fix, should still be applicable.

**Comment by avatsaev** [comment] 2016-09-07 06:32
okay, i gulped and pushed with the dist folder and it worked
