### ISSUE TITLE
Never get email after simple Heroku deployment

### ISSUE THREAD

**Issue by mdriess** [rauchg/slackin#38] opened 2015-04-14 19:43 UTC
![image](https://cloud.githubusercontent.com/assets/1505734/7145736/145e8d46-e2b4-11e4-9fe3-72b30edf558f.png)

Never get email after submitting... I did the plain vanilla Heroku deployment. Forgive me on this, but not sure what troubleshooting information to provide, so let me know where to look and what to provide.

**Comment by afeld** [comment] 2015-04-14 22:02
Ditto. Not seeing any errors in the logs or anything.

**Comment by ultrasaurus** [comment] 2015-04-15 13:37
@rauchg are the emails sent by slack?  is there something we need to do in the Slack admin to enable this?

**Comment by rauchg** [comment] 2015-04-15 19:36
@ultrasaurus they are. It could be related to the fact that it's a channel invite? I mostly test with full organization join.

**Comment by rauchg** [comment] 2015-04-15 19:36
Could be related to this which I recently merged a PR for:
https://github.com/rauchg/slackin/blob/master/lib/slack-invite.js#L8

@kishikawakatsumi can you confirm this works for you?

**Comment by afeld** [comment] 2015-04-15 21:11
@rauchg I was running `master`, so had that change in. Had the same problem without the `--channel` flag. Will try adding some more logging and see what the issue is.

**Comment by afeld** [comment] 2015-04-15 21:11
(I work w/ @ultrasaurus)

**Comment by pcolton** [comment] 2015-04-15 23:36
Seeing the same thing. I tried with our paid account and emails WORK, I tried it with a second account I created just for the task, a free account, and so far no emails. Same server, just changing SLACK_SUBDOMAIN to point to correct domain.

**Comment by pcolton** [comment] 2015-04-15 23:41
...so, I just upgraded to a paid plan and emails work now.

**Comment by afeld** [comment] 2015-04-16 00:08
Hmmmmm, `users.admin.invite` [isn't listed](https://github.com/slackhq/slack-api-docs/issues/22) in their [API docs](https://api.slack.com/methods). I only tried with an unpaid account...seems strange that there would be a difference there.

**Comment by rauchg** [comment] 2015-04-16 01:04
I've always used it with unpaid orgs myself.

**Comment by xzyfer** [comment] 2015-04-16 10:34
Also experiencing this issue with a free slack account.

**Comment by pcolton** [comment] 2015-04-16 16:51
So, it seems to be a limit on Slack's side, that is, per their docs, single-channel guests are:

"Free for paid teams (limited to 5 accounts per paying team member)"

So once you hit the limit, no more invite emails go out.

**Closed** 2015-04-16 18:00 UTC

**Comment by brucek** [comment] 2015-04-17 01:28
The real deal seems to be that if you restrict users by channel (single channel mode), you'll have account limit problems.  If you leave out the channel, it should work fine on free plans except that guests can see all channels.  Might be worth a mention in the docs.

**Comment by rauchg** [comment] 2015-04-17 02:01
@brucek def. Thanks for the extra clarification. Just updated the docs.

![image](https://cloud.githubusercontent.com/assets/13041/7194827/0d1252ee-e46b-11e4-9cb4-fcbbda863db6.png)

LGTY?

**Comment by SachaG** [comment] 2015-04-20 09:12
Leaving out the `SLACK_CHANNEL` env variable crashed my Heroku app. 

I ended up removing that variable completely from the Procfile, that seems to work (and I'm now finally receiving the invites! yay!).
